const {
  generateGroups,
  variance,
  countOccurrences,
  AllocationAlgorithm,
} = require("../algorithm/algorithm");

const students = [
  {
    _id: 1,
    firstName: "Alice",
    lastName: "Smith",
    gender: "female",
    fluentLanguages: ["English"],
    averageGrade: 72,
    skills: { programming: 7, research: 5, writing: 3, presenting: 3 },
    personality: { d: 3, i: 7, s: 1, c: 4 },
  },
  {
    _id: 2,
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 65,
    skills: { programming: 6, research: 4, writing: 6, presenting: 7 },
    personality: { d: 8, i: 3, s: 2, c: 4 },
  },
  {
    _id: 3,
    firstName: "Emma",
    lastName: "Johnson",
    gender: "female",
    fluentLanguages: ["English", "Spanish"],
    averageGrade: 78,
    skills: { programming: 7, research: 6, writing: 7, presenting: 6 },
    personality: { d: 2, i: 6, s: 4, c: 8 },
  },
  {
    _id: 4,
    firstName: "Liam",
    lastName: "Brown",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 53,
    skills: { programming: 3, research: 5, writing: 7, presenting: 1 },
    personality: { d: 7, i: 2, s: 3, c: 4 },
  },
  {
    _id: 5,
    firstName: "John",
    lastName: "Taylor",
    gender: "male",
    fluentLanguages: ["English", "French"],
    averageGrade: 60,
    skills: { programming: 4, research: 5, writing: 6, presenting: 2 },
    personality: { d: 5, i: 7, s: 3, c: 2 },
  },
  {
    _id: 6,
    firstName: "James",
    lastName: "Wilson",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 45,
    skills: { programming: 5, research: 3, writing: 3, presenting: 4 },
    personality: { d: 4, i: 3, s: 8, c: 2 },
  },
  {
    _id: 7,
    firstName: "Isaac",
    lastName: "Martinez",
    gender: "male",
    fluentLanguages: ["English", "Portuguese"],
    averageGrade: 73,
    skills: { programming: 6, research: 5, writing: 4, presenting: 5 },
    personality: { d: 2, i: 5, s: 3, c: 9 },
  },
  {
    _id: 8,
    firstName: "William",
    lastName: "Anderson",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 68,
    skills: { programming: 6, research: 6, writing: 3, presenting: 3 },
    personality: { d: 7, i: 2, s: 5, c: 1 },
  },
  {
    _id: 9,
    firstName: "Max",
    lastName: "Thomas",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 74,
    skills: { programming: 5, research: 7, writing: 5, presenting: 2 },
    personality: { d: 4, i: 8, s: 2, c: 1 },
  },
  {
    _id: 10,
    firstName: "Lucas",
    lastName: "Moore",
    gender: "male",
    fluentLanguages: ["English", "German"],
    averageGrade: 50,
    skills: { programming: 5, research: 5, writing: 7, presenting: 1 },
    personality: { d: 6, i: 4, s: 2, c: 8 },
  },
  {
    _id: 11,
    firstName: "Charlie",
    lastName: "White",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 79,
    skills: { programming: 7, research: 6, writing: 5, presenting: 3 },
    personality: { d: 3, i: 8, s: 1, c: 2 },
  },
  {
    _id: 12,
    firstName: "Ethan",
    lastName: "Harris",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 61,
    skills: { programming: 6, research: 3, writing: 5, presenting: 5 },
    personality: { d: 4, i: 2, s: 9, c: 1 },
  },
  {
    _id: 13,
    firstName: "Ali",
    lastName: "Clark",
    gender: "male",
    fluentLanguages: ["English", "Italian"],
    averageGrade: 77,
    skills: { programming: 6, research: 7, writing: 6, presenting: 6 },
    personality: { d: 5, i: 3, s: 4, c: 7 },
  },
  {
    _id: 14,
    firstName: "Noah",
    lastName: "Lewis",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 46,
    skills: { programming: 6, research: 3, writing: 4, presenting: 6 },
    personality: { d: 6, i: 5, s: 2, c: 7 },
  },
  {
    _id: 15,
    firstName: "Ava",
    lastName: "Walker",
    gender: "female",
    fluentLanguages: ["English", "Japanese"],
    averageGrade: 66,
    skills: { programming: 6, research: 4, writing: 3, presenting: 5 },
    personality: { d: 2, i: 4, s: 7, c: 5 },
  },
  {
    _id: 16,
    firstName: "Alexander",
    lastName: "Hall",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 57,
    skills: { programming: 4, research: 5, writing: 5, presenting: 4 },
    personality: { d: 8, i: 4, s: 2, c: 1 },
  },
  {
    _id: 17,
    firstName: "Emily",
    lastName: "Allen",
    gender: "female",
    fluentLanguages: ["English"],
    averageGrade: 71,
    skills: { programming: 7, research: 4, writing: 7, presenting: 5 },
    personality: { d: 3, i: 6, s: 1, c: 8 },
  },
  {
    _id: 18,
    firstName: "Benjamin",
    lastName: "Young",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 39,
    skills: { programming: 1, research: 1, writing: 3, presenting: 4 },
    personality: { d: 7, i: 2, s: 6, c: 3 },
  },
  {
    _id: 19,
    firstName: "Harper",
    lastName: "King",
    gender: "female",
    fluentLanguages: ["English"],
    averageGrade: 58,
    skills: { programming: 4, research: 6, writing: 2, presenting: 6 },
    personality: { d: 1, i: 9, s: 3, c: 4 },
  },
  {
    _id: 20,
    firstName: "Henry",
    lastName: "Wright",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 63,
    skills: { programming: 6, research: 6, writing: 5, presenting: 5 },
    personality: { d: 4, i: 3, s: 8, c: 5 },
  },
  {
    _id: 21,
    firstName: "Ella",
    lastName: "Scott",
    gender: "female",
    fluentLanguages: ["English", "Korean"],
    averageGrade: 75,
    skills: { programming: 6, research: 7, writing: 5, presenting: 6 },
    personality: { d: 2, i: 5, s: 4, c: 9 },
  },
  {
    _id: 22,
    firstName: "Michael",
    lastName: "Green",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 52,
    skills: { programming: 2, research: 2, writing: 2, presenting: 2 },
    personality: { d: 6, i: 4, s: 7, c: 1 },
  },
  {
    _id: 23,
    firstName: "Grace",
    lastName: "Adams",
    gender: "female",
    fluentLanguages: ["English"],
    averageGrade: 62,
    skills: { programming: 5, research: 4, writing: 7, presenting: 4 },
    personality: { d: 5, i: 8, s: 2, c: 3 },
  },
  {
    _id: 24,
    firstName: "Elijah",
    lastName: "Baker",
    gender: "male",
    fluentLanguages: ["English", "Russian"],
    averageGrade: 64,
    skills: { programming: 7, research: 7, writing: 5, presenting: 6 },
    personality: { d: 3, i: 7, s: 2, c: 5 },
  },
  {
    _id: 25,
    firstName: "Victoria",
    lastName: "Carter",
    gender: "female",
    fluentLanguages: ["English"],
    averageGrade: 69,
    skills: { programming: 7, research: 6, writing: 2, presenting: 5 },
    personality: { d: 4, i: 9, s: 1, c: 2 },
  },
  {
    _id: 26,
    firstName: "Daniel",
    lastName: "Perez",
    gender: "male",
    fluentLanguages: ["English", "Spanish"],
    averageGrade: 54,
    skills: { programming: 5, research: 5, writing: 4, presenting: 2 },
    personality: { d: 7, i: 5, s: 3, c: 4 },
  },
  {
    _id: 27,
    firstName: "George",
    lastName: "Long",
    gender: "male",
    fluentLanguages: ["English", "Mandarin"],
    averageGrade: 70,
    skills: { programming: 5, research: 6, writing: 5, presenting: 3 },
    personality: { d: 1, i: 8, s: 4, c: 6 },
  },
  {
    _id: 28,
    firstName: "Sebastian",
    lastName: "Hughes",
    gender: "male",
    fluentLanguages: ["English"],
    averageGrade: 42,
    skills: { programming: 4, research: 4, writing: 5, presenting: 6 },
    personality: { d: 6, i: 3, s: 7, c: 2 },
  },
  {
    _id: 29,
    firstName: "Abigail",
    lastName: "Ramirez",
    gender: "female",
    fluentLanguages: ["English"],
    averageGrade: 76,
    skills: { programming: 7, research: 6, writing: 6, presenting: 5 },
    personality: { d: 4, i: 7, s: 2, c: 5 },
  },
  {
    _id: 30,
    firstName: "Jackson",
    lastName: "Torres",
    gender: "male",
    fluentLanguages: ["English", "French"],
    averageGrade: 48,
    skills: { programming: 6, research: 5, writing: 7, presenting: 7 },
    personality: { d: 8, i: 4, s: 3, c: 5 },
  },
];

const criteria = [
  {
    attribute: "averageGrade",
    function: "classavg",
    goal: "similar",
    priority: 0.6,
  },
  {
    tag: "skill-coverage",
    skills: ["programming", "research", "writing", "presenting"],
    priority: 0.4,
    value: true,
  },
];

const penalties = [{ attribute: "gender", function: "alone", penalty: 0.5 }];

const groupings = [
  [1, 2, 3],
  [4, 5, 6],
];

// https://stackoverflow.com/a/57028486
let a = students.map((p) => p.gender);
// console.log(a.reduce((acc, e) => acc.set(e, (acc.get(e) || 0) + 1), new Map()));

let algo = new AllocationAlgorithm(students, criteria, penalties, 5, "minimum");
algo.createInitialPopulation();
// console.log(algo.population);

// console.log(algo.groupCriterionFitness([3,11,21,29], {"attribute": "averageGrade", "function": "classavg", "goal": "similar", "priority": 1}));
// console.log("");
// console.log(algo.groupCriterionFitness([27,24,29,30], {"attribute": "averageGrade", "function": "classavg", "goal": "similar", "priority": 1}));

// console.log(algo.allocationFitness([[1,5,6], [13,14,15]]));
// console.log(algo.allocationFitness([[1,2,3], [4,5,6]]));

algo.run();
let best = algo.population[0];
algo.logBestGroup();
